name: example
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.1
  uuid: ^3.0.5
  sqflite_sqlcipher: ^2.1.0
  tiki_style: ^0.0.9
  tiki_kv: ^0.1.1
  tiki_data:
    path: ../
  tiki_spam_cards: ^0.0.6
  tiki_decision: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any

dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override

flutter:
  uses-material-design: true

