name: example
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amplitude_flutter: 3.10.0
  logging: ^1.0.2
  uuid: ^3.0.6
  sqflite_sqlcipher: ^2.1.1
  tiki_style: ^0.0.20
  tiki_kv: ^0.1.1
  tiki_data:
    path: ../
  tiki_spam_cards: ^0.0.10
  tiki_decision: ^0.0.13
  tiki_wallet: ^0.0.26
  httpp: ^0.0.6
  tiki_localgraph: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any

dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override
  crypto: ^3.0.1

flutter:
  uses-material-design: true

