name: tiki_data
description: flutter sdk for data
version: 0.0.17
homepage: https://mytiki.com
repository: https://github.com/tiki/data
issue_tracker: https://github.com/tiki/data/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  amplitude_flutter: ^3.10.0
  logging: ^1.0.2
  provider: ^6.0.3
  sqflite_sqlcipher: ^2.1.1
  httpp: ^0.0.6
  pointycastle: ^3.6.0
  tiki_style: ^0.0.20
  tiki_strategy_google: ^0.1.10
  tiki_strategy_microsoft: ^0.1.10
  tiki_spam_cards: ^0.0.10
  tiki_decision: ^0.0.13
  tiki_localgraph: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

false_secrets:
  - lib/src/intg/intg_strategy_google.dart
  - lib/src/intg/intg_strategy_microsoft.dart
