name: tiki_data
description: flutter sdk for data
version: 0.0.7
homepage: https://mytiki.com
repository: https://github.com/tiki/data
issue_tracker: https://github.com/tiki/data/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.1
  provider: ^6.0.2
  tiki_style: ^0.0.17
  sqflite_sqlcipher: ^2.1.0
  httpp: ^0.0.3
  pointycastle: ^3.5.2
  tiki_strategy_google:
    path: ../strategy_google
  tiki_strategy_microsoft: ^0.1.2
  tiki_spam_cards: ^0.0.9
  tiki_decision: ^0.0.10
  tiki_localgraph:
    path: ../localgraph

dev_dependencies:
  flutter_test:
    sdk: flutter

false_secrets:
  - lib/src/intg/intg_strategy_google.dart
  - lib/src/intg/intg_strategy_microsoft.dart
