name: data
description: flutter sdk for data
version: 0.0.1
homepage: https://mytiki.com
repository: https://github.com/tiki/data
issue_tracker: https://github.com/tiki/data/issues
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.1
  provider: ^6.0.2
  tiki_style: ^0.0.5
  sqflite_sqlcipher: ^2.1.0
  httpp: ^0.0.3
  google_provider:
    path: ../google_provider
  microsoft_provider:
    path: ../microsoft_provider

dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override

dev_dependencies:
  flutter_test:
    sdk: flutter
